### PR TITLE
Extend unittest

### PR DESCRIPTION
**Pull request by lbusoni**

### CODE REVIEW

**Comment by lbusoni** [comment]
test_fake_angle_rotator doesn't work. Fix it see 0c0e309

**Comment by lbusoni** [comment]
Also add a test of ground/GUI.py

**Comment by ChiaraSelmi** [comment]
"Process completed with exit code 134."

@lbusoni quando hai un attimo potresti darci un'occhiata?

**Comment by lbusoni** [comment]
It's a crash (not an error, a real python segmentation fault) due to some import related to guietta
It looks like adding guietta (and PySide as a consequence) introduced some issues. Alfio has documented the thing here https://guietta.readthedocs.io/en/latest/qt_conda.html
If this is confirmed to be the issue we may try to follow Alfio's suggestion of not mixing up conda and pip

**Comment by lbusoni** [comment]
I tried to update the setup of in python-package by adding "conda install -c conda-forge pyside2" but it didn't get any better and the test is still crashing on guietta. @alfiopuglisi, could you give us some hints?

**Comment by alfiopuglisi** [comment]
Running a test with GUIs is very difficult since the default GitHub VM does not have any graphics driver. If you look at https://github.com/alfiopuglisi/guietta/blob/master/.github/workflows/pytest.yml you see that I had to:
 1) sudo make install of a lot of system packages before running the tests
 2) run the tests using "xvfb-run pytest" instead of just pytest, in order to use a virtual framebuffer

In your test output I see the log of pip installing everything, but I do not see the output of conda installing pyside2. Are you sure it is being run? Anyway on the github tests conda is not used, as far as I know, so this installation should not be needed.

**Pull request merged**
